export const START_LESSON = 'LESSON/START_LESSON';
export const PAUSE_LESSON = 'LESSON/PAUSE_LESSON';
export const RESUME_LESSON = 'LESSON/RESUME_LESSON';
export const STOP_LESSON = 'LESSON/STOP_LESSON';
export const CLEAN_LESSON = 'LESSON/CLEAN_LESSON';