export const RESET_TEXT = 'TEXT/RESET_TEXT';
export const SHOW_ERROR = 'TEXT/SHOW_ERROR';
export const HIDE_ERROR = 'TEXT/HIDE_ERROR';
export const PUSHED_CORRECTLY_KEY = 'TEXT/PUSHED_CORRECTLY_KEY';
export const PUSHED_WRONG_SYMBOL = 'TEXT/PUSHED_WRONG_SYMBOL';