export const SET_LEARNING_KEY = 'SETTING/SET_LEARNING_KEY';
export const REMOVE_LEARNING_KEY = 'SETTING/REMOVE_LEARNING_KEY';
export const SHOW_SETTINGS = 'SETTING/SHOW_SETTINGS';
export const HIDE_SETTINGS = 'SETTING/HIDE_SETTINGS';
export const INCREMENT_TEXT_LENGTH = 'SETTING/INCREMENT_TEXT_LENGTH';
export const DECREMENT_TEXT_LENGTH = 'SETTING/DECREMENT_TEXT_LENGTH';
export const SET_MAX_WORD_LENGTH = 'SETTING/SET_MAX_WORD_LENGTH';